UPDATE ecommerce.text SET title = '苹果手机里有多少隐藏小功能？——1、iphone备忘录功能', length = 1, text1 = 'iPhone隐藏小技巧双手奉上，没学的后悔到哭！！！', type = 1;
UPDATE ecommerce.text SET title = '苹果手机里有多少隐藏小功能？——2、备忘录设置密码', length = 2, text1 = 'iPhone隐藏小技巧双手奉上，没学的后悔到哭！！！', type = 1;
UPDATE ecommerce.text SET title = '苹果手机里有多少隐藏小功能？——3、截图', length = 3, text1 = 'iPhone隐藏小技巧双手奉上，没学的后悔到哭！！！', type = 1;
UPDATE ecommerce.text SET title = '苹果手机里有多少隐藏小功能？——4、录屏', length = 4, text1 = 'iPhone隐藏小技巧双手奉上，没学的后悔到哭！！！', type = 1;
UPDATE ecommerce.text SET title = '苹果手机里有多少隐藏小功能？——5、录屏带声音', length = 5, text1 = 'iPhone隐藏小技巧双手奉上，没学的后悔到哭！！！', type = 1;
UPDATE ecommerce.text SET title = '苹果手机里有多少隐藏小功能？——6、汇率', length = 6, text1 = 'iPhone隐藏小技巧双手奉上，没学的后悔到哭！！！', type = 1;
UPDATE ecommerce.text SET title = '苹果手机里有多少隐藏小功能？——8、自带字典', length = 8, text1 = 'iPhone隐藏小技巧双手奉上，没学的后悔到哭！！！', type = 1;
UPDATE ecommerce.text SET title = '苹果手机里有多少隐藏小功能？——9、自动续费项目', length = 9, text1 = 'iPhone隐藏小技巧双手奉上，没学的后悔到哭！！！', type = 1;
UPDATE ecommerce.text SET title = '苹果手机里有多少隐藏小功能？——10、生日', length = 10, text1 = 'iPhone隐藏小技巧双手奉上，没学的后悔到哭！！！', type = 1;
UPDATE ecommerce.text SET title = '苹果手机里有多少隐藏小功能？——11、撤销删除', length = 11, text1 = 'iPhone隐藏小技巧双手奉上，没学的后悔到哭！！！', type = 1;
UPDATE ecommerce.text SET title = '苹果手机里有多少隐藏小功能？——12、计算器删除', length = 12, text1 = 'iPhone隐藏小技巧双手奉上，没学的后悔到哭！！！', type = 1;
UPDATE ecommerce.text SET title = '苹果手机里有多少隐藏小功能？——13、关闭app评分', length = 13, text1 = 'iPhone隐藏小技巧双手奉上，没学的后悔到哭！！！', type = 1;
UPDATE ecommerce.text SET title = '苹果手机里有多少隐藏小功能？——14、自定义控制中心', length = 14, text1 = 'iPhone隐藏小技巧双手奉上，没学的后悔到哭！！！', type = 1;
UPDATE ecommerce.text SET title = '苹果手机里有多少隐藏小功能？——15、4K视频拍摄', length = 15, text1 = 'iPhone隐藏小技巧双手奉上，没学的后悔到哭！！！', type = 1;
UPDATE ecommerce.text SET title = '苹果手机里有多少隐藏小功能？——16、相机九宫格', length = 16, text1 = 'iPhone隐藏小技巧双手奉上，没学的后悔到哭！！！', type = 1;
UPDATE ecommerce.text SET title = '苹果手机里有多少隐藏小功能？——17、隐藏照片', length = 17, text1 = 'iPhone隐藏小技巧双手奉上，没学的后悔到哭！！！', type = 1;
UPDATE ecommerce.text SET title = '苹果手机里有多少隐藏小功能？——18、快速调出付款吗', length = 18, text1 = 'iPhone隐藏小技巧双手奉上，没学的后悔到哭！！！', type = 1;
UPDATE ecommerce.text SET title = '苹果手机里有多少隐藏小功能？——19、Airdrop', length = 19, text1 = 'iPhone隐藏小技巧双手奉上，没学的后悔到哭！！！', type = 1;
UPDATE ecommerce.text SET title = '苹果手机里有多少隐藏小功能？——20、关闭所有Safari', length = 20, text1 = 'iPhone隐藏小技巧双手奉上，没学的后悔到哭！！！', type = 1;
UPDATE ecommerce.text SET title = 'Surface 比 iPad 好在哪里？——1、屏幕大小', length = 21, text1 = '无论是在书房办公、还是在厨房餐桌，客厅沙发办公，Surface 都能助您完成工作。Surface 具备高分辨率触控屏和Dolby® Audio™ 音效，适合聆听音乐，观看视频节目；配备高清摄像头，方便视频通话，随时保持联络；同时搭载您所熟悉的Windows系统。', type = 1;
UPDATE ecommerce.text SET title = 'Surface 比 iPad 好在哪里？——2、系统', length = 22, text1 = '无论是在书房办公、还是在厨房餐桌，客厅沙发办公，Surface 都能助您完成工作。Surface 具备高分辨率触控屏和Dolby® Audio™ 音效，适合聆听音乐，观看视频节目；配备高清摄像头，方便视频通话，随时保持联络；同时搭载您所熟悉的Windows系统。', type = 1;
UPDATE ecommerce.text SET title = 'Surface 比 iPad 好在哪里？——3、触控笔', length = 23, text1 = '无论是在书房办公、还是在厨房餐桌，客厅沙发办公，Surface 都能助您完成工作。Surface 具备高分辨率触控屏和Dolby® Audio™ 音效，适合聆听音乐，观看视频节目；配备高清摄像头，方便视频通话，随时保持联络；同时搭载您所熟悉的Windows系统。', type = 1;
UPDATE ecommerce.text SET title = 'Surface 比 iPad 好在哪里？——4、充电和续航', length = 24, text1 = '无论是在书房办公、还是在厨房餐桌，客厅沙发办公，Surface 都能助您完成工作。Surface 具备高分辨率触控屏和Dolby® Audio™ 音效，适合聆听音乐，观看视频节目；配备高清摄像头，方便视频通话，随时保持联络；同时搭载您所熟悉的Windows系统。', type = 1;
UPDATE ecommerce.text SET title = 'Surface 比 iPad 好在哪里？——5、方便上网', length = 25, text1 = '无论是在书房办公、还是在厨房餐桌，客厅沙发办公，Surface 都能助您完成工作。Surface 具备高分辨率触控屏和Dolby® Audio™ 音效，适合聆听音乐，观看视频节目；配备高清摄像头，方便视频通话，随时保持联络；同时搭载您所熟悉的Windows系统。', type = 1;
UPDATE ecommerce.text SET title = 'Surface 比 iPad 好在哪里？——6、方便录课', length = 26, text1 = '无论是在书房办公、还是在厨房餐桌，客厅沙发办公，Surface 都能助您完成工作。Surface 具备高分辨率触控屏和Dolby® Audio™ 音效，适合聆听音乐，观看视频节目；配备高清摄像头，方便视频通话，随时保持联络；同时搭载您所熟悉的Windows系统。', type = 1;
UPDATE ecommerce.text SET title = 'Surface 比 iPad 好在哪里？——7、有触控板', length = 27, text1 = '无论是在书房办公、还是在厨房餐桌，客厅沙发办公，Surface 都能助您完成工作。Surface 具备高分辨率触控屏和Dolby® Audio™ 音效，适合聆听音乐，观看视频节目；配备高清摄像头，方便视频通话，随时保持联络；同时搭载您所熟悉的Windows系统。', type = 1;
UPDATE ecommerce.text SET title = 'Surface 比 iPad 好在哪里？——8、可以无线投影', length = 28, text1 = '无论是在书房办公、还是在厨房餐桌，客厅沙发办公，Surface 都能助您完成工作。Surface 具备高分辨率触控屏和Dolby® Audio™ 音效，适合聆听音乐，观看视频节目；配备高清摄像头，方便视频通话，随时保持联络；同时搭载您所熟悉的Windows系统。', type = 1;
UPDATE ecommerce.text SET title = 'Surface 比 iPad 好在哪里？——9、发热', length = 29, text1 = '无论是在书房办公、还是在厨房餐桌，客厅沙发办公，Surface 都能助您完成工作。Surface 具备高分辨率触控屏和Dolby® Audio™ 音效，适合聆听音乐，观看视频节目；配备高清摄像头，方便视频通话，随时保持联络；同时搭载您所熟悉的Windows系统。', type = 1;
UPDATE ecommerce.text SET title = 'Surface 比 iPad 好在哪里？——10、摄像头', length = 30, text1 = '无论是在书房办公、还是在厨房餐桌，客厅沙发办公，Surface 都能助您完成工作。Surface 具备高分辨率触控屏和Dolby® Audio™ 音效，适合聆听音乐，观看视频节目；配备高清摄像头，方便视频通话，随时保持联络；同时搭载您所熟悉的Windows系统。', type = 1;
UPDATE ecommerce.text SET title = 'Surface 比 iPad 好在哪里？——11、屏幕质量', length = 31, text1 = '无论是在书房办公、还是在厨房餐桌，客厅沙发办公，Surface 都能助您完成工作。Surface 具备高分辨率触控屏和Dolby® Audio™ 音效，适合聆听音乐，观看视频节目；配备高清摄像头，方便视频通话，随时保持联络；同时搭载您所熟悉的Windows系统。', type = 1;
UPDATE ecommerce.text SET title = 'Surface 比 iPad 好在哪里？——12、售后', length = 32, text1 = '无论是在书房办公、还是在厨房餐桌，客厅沙发办公，Surface 都能助您完成工作。Surface 具备高分辨率触控屏和Dolby® Audio™ 音效，适合聆听音乐，观看视频节目；配备高清摄像头，方便视频通话，随时保持联络；同时搭载您所熟悉的Windows系统。', type = 1;
UPDATE ecommerce.text SET title = 'Surface 比 iPad 好在哪里？——13、OneDrive', length = 33, text1 = '无论是在书房办公、还是在厨房餐桌，客厅沙发办公，Surface 都能助您完成工作。Surface 具备高分辨率触控屏和Dolby® Audio™ 音效，适合聆听音乐，观看视频节目；配备高清摄像头，方便视频通话，随时保持联络；同时搭载您所熟悉的Windows系统。', type = 1;
UPDATE ecommerce.text SET title = 'Surface 比 iPad 好在哪里？——14、外壳', length = 34, text1 = '无论是在书房办公、还是在厨房餐桌，客厅沙发办公，Surface 都能助您完成工作。Surface 具备高分辨率触控屏和Dolby® Audio™ 音效，适合聆听音乐，观看视频节目；配备高清摄像头，方便视频通话，随时保持联络；同时搭载您所熟悉的Windows系统。', type = 1;
UPDATE ecommerce.text SET title = '小米9号Plus平衡车体验：脚感有何不同？', length = 35, text1 = '这次产品我也是发布会结束才拿到的，用了4天左右，总体感觉产品是OK的，但是依然没有让我对平衡车这个类型的市场有更强的信心...这样说我有一些伤感，因为我个人还是很喜欢这类产品的，好像只要是酷的东西...我也没有哪个是不喜欢的吧～～哈哈哈哈哈哈哈～晚安！', type = 2;
UPDATE ecommerce.text SET title = '轻薄本最强CPU锐龙R7-4800U，联想YOGA14S开箱', length = 36, text1 = '中正评测：轻薄本最强CPU锐龙R7-4800U，联想YOGA14S开箱', type = 2;
UPDATE ecommerce.text SET title = '哪款适合你？iPad mini 5和iPad Air 3深度体验', length = 37, text1 = 'BGM：Distractions —— Groenland Stronger——Kanye West 感谢同学们愿意借给我iPad拍', type = 2;